import type { Woordenboek } from "./nl";

/**
 * The English interface texts. Same shape as nl.ts; the type keeps the two in
 * step. Plain British English, "you", short sentences, no dashes. Dutch legal
 * terms get their Dutch name in brackets the first time they appear (see the
 * glossary in docs/adr/0001-tweetalig-nl-en.md).
 */
export const en: Woordenboek = {
  taal: "en",
  locale: "en-GB",
  ogLocale: "en_GB",

  algemeen: {
    naarInhoud: "Skip to content",
    menuOpenen: "Open menu",
    menuSluiten: "Close menu",
    menu: "Menu",
    home: "Home",
    kruimelpad: "Breadcrumb",
    bellen: "Call",
    mailen: "Email",
    belOns: "Call us: {tel}",
    openingstijden: "Monday to Friday, 9:00 to 17:00",
    optioneel: "optional",
    leesMeer: "Find out more",
    alleenNederlands: " (Dutch)",
    taal: "Language",
    klanten: "Clients",
    talen: { nl: "Nederlands", en: "English" },
    talenKort: { nl: "NL", en: "EN" },
  },

  header: {
    werkgevers: "Employers",
    werknemers: "Employees",
    kiesDoelgroep: "Choose your route",
    logoNaarHome: "React2u, to the homepage",
    naarBegin: "React2u for {naam}, to the start",
    hoofdmenu: "Main menu",
    menuVoor: "Menu for {naam}",
    doelgroepNaam: { werkgever: "employers", werknemer: "employees" },
    toplinks: [
      { label: "About us", slug: "over-react2u" },
      { label: "Careers", slug: "vacatures" },
      { label: "Contact", slug: "contact" },
    ],
    menuNeutraal: [
      { label: "Employers", slug: "werkgevers" },
      { label: "Employees", slug: "werknemers" },
      { label: "About us", slug: "over-react2u", overOns: true },
      { label: "Contact", slug: "contact" },
    ],
    overOns: [
      { label: "About React2u", slug: "over-react2u" },
      { label: "Careers", slug: "vacatures" },
      { label: "Certifications", slug: "certificeringen" },
    ],
    overOnsKop: "About React2u",
    diensten: [
      { naam: "Resist", sub: "Prevention and vitality", slug: "resist", kleur: "#00A098" },
      { naam: "Recover", sub: "Sickness absence support", slug: "recover", kleur: "#E61674" },
      { naam: "Restart", sub: "Reintegration and careers", slug: "restart", kleur: "#F19001" },
      { naam: "Reflex", sub: "Temporary staffing and the Sickness Benefits Act", slug: "reflex", kleur: "#3AA5DD" },
      { naam: "Ready", sub: "HR and employment law", slug: "ready", kleur: "#322E83" },
    ],
    menuWerkgever: [
      { label: "Services", slug: "werkgevers", anker: "services", diensten: true },
      { label: "How we work", slug: "werkgevers", anker: "how-we-work" },
      { label: "Pricing", slug: "werkgevers", anker: "pricing" },
      { label: "Switching to us", slug: "werkgevers", anker: "switching" },
      { label: "FAQ", slug: "werkgevers", anker: "faq" },
    ],
    menuWerknemer: [
      { label: "Sick, what now?", slug: "verzuimprotocol" },
      { label: "Your rights", slug: "je-rechten-en-privacy" },
      { label: "Your case manager", slug: "je-casemanager" },
      { label: "FAQ", slug: "werknemers", anker: "faq" },
    ],
    knop: {
      neutraal: { label: "Let's talk", slug: "kennismaken" },
      werkgever: { label: "Let's talk", slug: "kennismaken" },
      werknemer: { label: "Call your case manager", slug: "tel:" },
    },
    inloggen: "Log in",
    portalen: {
      werkgever: { label: "Employer portal", sub: "Follow absence, report sick and recovered" },
      werknemer: { label: "My file", sub: "Appointments and documents for employees" },
    },
  },

  footer: {
    bezoekadres: "Visiting address",
    contact: "Contact",
    alleContactgegevens: "All contact details",
    voorWerkgevers: "For employers",
    voorWerknemers: "For employees",
    werkgeverLinks: [
      { label: "Services", slug: "werkgevers", anker: "services" },
      { label: "Pricing", slug: "verzuimabonnementen" },
      { label: "Let's talk", slug: "kennismaken" },
    ],
    werknemerLinks: [
      { label: "Sick, what now?", slug: "verzuimprotocol" },
      { label: "Your rights and privacy", slug: "je-rechten-en-privacy" },
      { label: "Your case manager", slug: "je-casemanager" },
    ],
    rechten: "© {jaar} React2u II B.V. All rights reserved. · Chamber of Commerce (KvK) {kvk}",
    documenten: {
      privacy: "Privacy statement",
      voorwaarden: "Terms and conditions",
      klachten: "Complaints procedure",
      cookies: "Cookie statement",
    },
    cookieInstellingen: "Cookie settings",
    sitemap: "",
    keurmerken: "Certifications and quality marks",
    keurmerkAlts: ["SBCA certified occupational health service", "DNV ISO 9001 certificate", "DNV ISO 27001 certificate", "DNV ISO 27701 certificate", "Member of OVAL"],
    logoNaarHome: "React2u, to the homepage",
  },

  cookies: {
    titel: "Cookies on react2u.nl",
    info: "We only use functional cookies. They are needed to make the site work properly and safely. We do not track you and we do not place third-party cookies.",
    toestemming: "We use functional cookies to make the site work. With your consent we also use other cookies. You can change your choice at any time via Cookie settings at the bottom of the page.",
    lees: "Read the cookie statement (Dutch)",
    prima: "OK",
    functioneel: "Functional",
    functioneelUitleg: "Needed for the site to work properly and safely. Always on.",
    keuzeOpslaan: "Save choice",
    weigeren: "Decline",
    instellingen: "Settings",
    accepteren: "Accept",
  },

  nietGevonden: {
    titel: "Page not found",
    eyebrow: "Page not found",
    tekst: "The page you are looking for does not exist any more, or it has moved. Don't worry, we are happy to help you further.",
    sterk: "This page is lost. We are not.",
    rest: "Go back to the homepage or get in touch.",
    naarHome: "To the homepage",
    contact: "Contact",
  },

  formulier: {
    naam: "Name",
    naamPlaceholder: "Your first and last name",
    email: "Email address",
    emailPlaceholder: "name@example.com",
    telefoon: "Phone number",
    telefoonPlaceholder: "+31 6 12345678",
    organisatie: "Organisation",
    organisatiePlaceholder: "Name of your organisation",
    bericht: "Message",
    berichtPlaceholder: "How can we help you?",
    onderwerp: "Subject",
    optioneel: "optional",
    verplichteVelden: "Fields marked with * are required.",
    bezig: "Sending…",
    versturen: "Send",
    privacy: "Privacy (Dutch)",
    privacyverklaring: "privacy statement (Dutch)",
    honeypot: "website",
    sollicitatie: {
      kop: "Apply in a few minutes",
      kopDirect: "Apply now",
      duur2: "2 minutes",
      duur1: "1 minute",
      ikSolliciteerOp: "I am applying for",
      open: "Open application",
      cv: "CV",
      cvOptioneel: "(optional, you can also send it later)",
      cvHint: "PDF or Word, up to 8 MB",
      verstuur: "Send application",
      bedankt: "Thank you for your application",
      bedanktTekst: "You will hear from us within five working days.",
      privacyVoor: "We handle your details with care. Read our ",
      privacyLink: "privacy statement (Dutch)",
      privacyNa: ".",
    },
    contact: {
      kop: "Send a message",
      bedankt: "Thank you for your message",
      bedanktTekst: "We will contact you within one working day.",
      geenMedisch: "Please do not share medical information here.",
      naamPlaceholder: "First and last name",
      emailPlaceholder: "name@company.com",
      telefoonPlaceholder: "+31 6 12 34 56 78",
    },
    fouten: {
      contactVerplicht: "Please fill in your name, email address, phone number and message.",
      algemeen: "Something went wrong. Please try again later.",
      sollicitatieVerplicht: "Please fill in at least your name and email address.",
      cvTeGroot: "Your CV is too large (max 8 MB).",
      cvType: "Please upload your CV as a PDF or Word file.",
      cvUpload: "Uploading your CV did not work. Please try again.",
      sollicitatieAlgemeen: "Something went wrong while sending. Please try again later.",
      offerteVerplicht: "Please fill in your name, company name, email address, phone number and the number of employees.",
    },
  },

  vacatures: {
    seo: {
      titel: "Careers",
      omschrijving: "Would you like to work at React2u? See our open vacancies and join the personal occupational health service in Eindhoven.",
      openTitel: "Open application",
      openOmschrijving: "Send an open application to React2u. We are always happy to hear from talented people.",
    },
    kruimelWerkenBij: "Careers",
    kruimelVacatures: "Vacancies",
    eyebrow: "Working at React2u",
    kop: "Help us build healthy and sustainable work",
    intro: "At React2u you help employees who are off sick get back to work, and you help employers keep control of sickness absence. Work that matters, every day.",
    bekijkVacatures: "See vacancies",
    openSollicitatie: "Open application",
    micro: ["Apply in 2 minutes", "No cover letter needed", "Reply within 5 working days"],
    openVacatures: "Open vacancies",
    nOpen: "{n} open",
    klantenLabel: "You will work for organisations such as",
    voordelenEyebrow: "What we offer you",
    voordelenKop: "An employer you can count on",
    voordelen: [
      { titel: "Terms of employment", tekst: "Our own terms of employment, tailored to our profession and our team." },
      { titel: "Training and development", tekst: "Training and guidance to keep growing in your profession." },
      { titel: "Your own caseload", tekst: "You build a bond with your clients and their people, as their regular contact." },
      { titel: "A proper start", tekst: "You start alongside experienced colleagues who show you the ropes." },
      { titel: "Close contact with the company doctor", tekst: "You work closely with the company doctor (bedrijfsarts), including under task delegation." },
      { titel: "An office in the heart of Eindhoven", tekst: "A committed team a short walk from the city centre, where things move quickly." },
    ],
    werkEyebrow: "Your work",
    werkKop: "Personal, with structure around it",
    werkTekst: "You are the link between the employer, the employee and the company doctor. You keep control of the absence case and make sure everyone knows the next step.",
    werkPunten: [
      "Conversations with employees and managers, on site or online",
      "Working in line with the Gatekeeper Improvement Act (Wet verbetering poortwachter), with clear processes",
      "Everything in one online file, so you keep the overview",
      "Bringing in the right help, from a labour expert (arbeidsdeskundige) to a coach",
    ],
    vacaturesEyebrow: "Vacancies",
    vacaturesKop: "Come and join our team",
    geenVacaturesKop: "No open vacancies right now",
    vacaturesTekst: "We are growing our team. We are looking for new colleagues for these roles.",
    geenVacaturesTekst: "But we are always happy to hear from talented people.",
    openKaartKop: "Open application",
    openKaartTekst: "Tell us who you are and what you are looking for. We will always get in touch.",
    openKaartLink: "Send your application",
    procesEyebrow: "Application process",
    procesKop: "How to apply",
    procesTekst: "Clear and personal. You know where you stand at every step.",
    stappen: [
      { titel: "Apply", tekst: "Send your CV and a short motivation via the vacancy." },
      { titel: "Introduction", tekst: "A first conversation at our office." },
      { titel: "Second interview", tekst: "We go deeper into the role and you meet the team." },
      { titel: "Offer", tekst: "A good match? Then we discuss your contract and start date." },
    ],
    solliciterenEyebrow: "Apply",
    solliciterenKop: "Would you like to work with us?",
    solliciterenTekst: "Choose the role and leave your details. You will hear from us within five working days. Prefer to talk first? Call or email Susanne.",
    solliciterenMicro: ["No cover letter", "Happy to meet first"],
    aanspreekpunt: "Your contact",
    susanneRol: "Managing director",
    inHetNederlands: "This vacancy is in Dutch",
    inHetNederlandsKort: "In Dutch",
    detail: {
      solliciteerDirect: "Apply now",
      duurtMinuut: "Takes a minute",
      belangrijkste: "The essentials",
      brutoPerMaand: "Gross per month, depending on experience",
      perWeek: "Per week, by arrangement",
      locatieSub: "At the office, on site and online",
      werkdagen: "5 working days",
      danHoorJe: "Then you will hear from us",
      locatie: "Location",
      uren: "Hours",
      salaris: "Salary",
      dienstverband: "Employment type",
      vragenBel: "Questions? Call Susanne",
      solliciterenKop: "Applying takes a minute",
      solliciterenTekst: "Leave your details and upload your CV. You will hear from us within five working days. No cover letter needed.",
      bekijkOok: "See also",
      allesOverWerken: "All about working at React2u",
      bekijkVacature: "View vacancy",
      openKaartTekst: "Can't see your role? Tell us who you are and what you are looking for.",
      altijdWelkom: "Always welcome",
      standaardLocatie: "Eindhoven",
    },
    dienstverband: {
      FULL_TIME: "Full-time",
      PART_TIME: "Part-time",
      "FULL_TIME,PART_TIME": "Full-time or part-time",
      CONTRACTOR: "Freelance",
      TEMPORARY: "Temporary",
      INTERN: "Internship",
    },
    openPagina: {
      eyebrow: "Working at React2u",
      kop: "Open application",
      tekst: "Can't see your role, but think you would fit in with us? We would love to hear from you. Leave your details and upload your CV.",
      formKop: "Tell us who you are",
    },
  },

  werkgevers: {
    poortwachterMoment: "When",
    poortwachterJij: "You as the employer",
    poortwachterWij: "React2u",
    tarievenKruimel: "Pricing",
    offerteAanvragen: "Request a quote",
    certificeringenKruimel: "Certifications",
    overOnsKruimel: "About us",
    overReact2uKruimel: "About React2u",
    kernwaarden: "Core values",
  },

  dienstLabel: {
    kruimelDiensten: "Services",
    adviesgesprek: "Talk to an adviser",
    alleDiensten: "All services",
    watJeKrijgt: "What you get",
    herken: "Does this sound familiar?",
    danIs: "Then React2u {naam} is there for you.",
    omvat: "What React2u {naam} includes",
    omvatTekst: "We can provide one part on its own, or combine them into an approach that fits your organisation.",
    aanpak: "Our approach",
    waarom: "Why React2u {naam}",
    gecertificeerd: "Certified and affiliated",
    bekijkOok: "See also",
    bekijk: "View",
  },

  gedeeld: {
    klantenLabel: "We work with:",
    ervaringenEyebrow: "What clients say",
    ervaringenKop: "What clients say about us",
    citaten: [
      {
        tekst: "Short lines, quick communication and always willing to think along. A pleasant occupational health service with an eye for both employer and employee.",
        naam: "Maxime Boonstra", rol: "Managing director, Kester staffing agency", logo: "/beeld/klanten/kester.png",
      },
      {
        tekst: "In a fast-moving supermarket organisation, acting quickly is essential. Thanks to the short lines, expert guidance and personal approach, we find working together very pleasant and reliable.",
        naam: "HR department", rol: "De Jumbo’s van Ralf & René", logo: "/beeld/klanten/jumbo.png",
      },
    ],
    kwaliteit: "Quality",
    getoetst: "Tested and certified",
    kwaliteitTekst: "You work with sensitive information. That is why we have our quality, security and privacy tested independently.",
    meerCertificeringen: "More about our certifications",
    keurmerken: [
      { naam: "SBCA", wat: "Certified occupational health service" },
      { naam: "ISO 9001", wat: "Quality management" },
      { naam: "ISO 27001", wat: "Information security" },
      { naam: "ISO 27701", wat: "Privacy" },
      { naam: "OVAL", wat: "Trade association" },
    ],
  },

  kennismaken: {
    kruimel: "Let's talk",
    eyebrow: "Introduction and quote",
    kop: "Shall we talk?",
    formKop: "Request a quote",
    bedrijfsnaam: "Company name",
    bedrijfsnaamPlaceholder: "Name of your organisation",
    naamPlaceholder: "First and last name",
    functie: "Job title",
    functiePlaceholder: "For example HR manager",
    emailPlaceholder: "name@company.com",
    telefoonPlaceholder: "+31 6 12 34 56 78",
    aantal: "Number of employees",
    maakKeuze: "Please choose",
    aantallen: ["1 to 10", "11 to 50", "51 to 100", "101 to 250", "More than 250"],
    interesse: "Interested in",
    interessePlaceholder: "For example sickness absence support",
    toelichting: "Comments",
    toelichtingPlaceholder: "How can we help you?",
    verstuur: "Send request",
    voet: "Your request goes to our sales team at sales@react2u.nl. We only use your details to contact you.",
    lieverBellen: "Prefer to call?",
    bedankt: "Thank you for your request",
    bedanktTekst: "We will contact you within two working days to get to know each other.",
  },

  seo: {
    siteOmschrijving: "React2u is a personal occupational health service (arbodienst) in Eindhoven. One regular case manager for employers and employees, from prevention to reintegration.",
    homeTitel: "Home • React2u",
    merk: "React2u",
  },
};
