/**
 * Alle vaste interfaceteksten van de publieke site in het Nederlands: header,
 * menu's, footer, cookiemelding, 404, kruimelpad, formulieren en de pagina's
 * rond vacatures. De Engelse tegenhanger staat in en.ts en moet dezelfde vorm
 * hebben (type Woordenboek). Teksten uit de blokdata (src/content) staan hier
 * niet: die zijn per taal een eigen JSON-bestand.
 *
 * `{naam}`-plekken vul je met vul() uit lib/taal.ts. Een `slug` is altijd de
 * Nederlandse slug uit de koppeltabel (lib/taal.ts); pad() maakt er het juiste
 * adres van. `anker` is het #-anker op die pagina, en verschilt per taal.
 */
export const nl = {
  taal: "nl",
  locale: "nl-NL",
  ogLocale: "nl_NL",

  algemeen: {
    naarInhoud: "Naar de inhoud",
    menuOpenen: "Menu openen",
    menuSluiten: "Menu sluiten",
    menu: "Menu",
    home: "Home",
    kruimelpad: "Kruimelpad",
    bellen: "Bellen",
    mailen: "Mailen",
    belOns: "Bel ons: {tel}",
    openingstijden: "Ma t/m vr 9.00 tot 17.00 uur",
    optioneel: "optioneel",
    leesMeer: "Lees meer",
    /** Achter een document dat alleen in het Nederlands bestaat; leeg in het Nederlands zelf. */
    alleenNederlands: "",
    taal: "Taal",
    klanten: "Klanten",
    talen: { nl: "Nederlands", en: "English" },
    talenKort: { nl: "NL", en: "EN" },
  },

  header: {
    werkgevers: "Werkgevers",
    werknemers: "Werknemers",
    kiesDoelgroep: "Kies je doelgroep",
    logoNaarHome: "React2u, naar de homepage",
    naarBegin: "React2u voor {naam}, naar het begin",
    hoofdmenu: "Hoofdmenu",
    menuVoor: "Menu {naam}",
    doelgroepNaam: { werkgever: "werkgevers", werknemer: "werknemers" },
    toplinks: [
      { label: "Over ons", slug: "over-react2u" },
      { label: "Werken bij", slug: "vacatures" },
      { label: "Contact", slug: "contact" },
    ],
    menuNeutraal: [
      { label: "Werkgevers", slug: "werkgevers" },
      { label: "Werknemers", slug: "werknemers" },
      { label: "Over ons", slug: "over-react2u", overOns: true },
      { label: "Contact", slug: "contact" },
    ] as { label: string; slug: string; overOns?: boolean }[],
    overOns: [
      { label: "Over React2u", slug: "over-react2u" },
      { label: "Werken bij", slug: "vacatures" },
      { label: "Certificeringen", slug: "certificeringen" },
      { label: "Blog", slug: "blog" },
    ],
    overOnsKop: "Over React2u",
    /** De vijf labels in het uitklapmenu Diensten. */
    diensten: [
      { naam: "Resist", sub: "Preventie en vitaliteit", slug: "resist", kleur: "#00A098" },
      { naam: "Recover", sub: "Verzuimbegeleiding", slug: "recover", kleur: "#E61674" },
      { naam: "Restart", sub: "Re-integratie en loopbaan", slug: "restart", kleur: "#F19001" },
      { naam: "Reflex", sub: "Flexbranche en Ziektewet", slug: "reflex", kleur: "#3AA5DD" },
      { naam: "Ready", sub: "HR en arbeidsrecht", slug: "ready", kleur: "#322E83" },
    ],
    menuWerkgever: [
      { label: "Diensten", slug: "werkgevers", anker: "diensten", diensten: true },
      { label: "Werkwijze", slug: "werkgevers", anker: "werkwijze" },
      { label: "Tarieven", slug: "werkgevers", anker: "tarieven" },
      { label: "Overstappen", slug: "werkgevers", anker: "starten" },
      { label: "Vragen", slug: "werkgevers", anker: "vragen" },
    ] as { label: string; slug: string; anker?: string; diensten?: boolean }[],
    menuWerknemer: [
      { label: "Ziek, wat nu?", slug: "verzuimprotocol" },
      { label: "Je rechten", slug: "je-rechten-en-privacy" },
      { label: "Je casemanager", slug: "je-casemanager" },
      { label: "Vragen", slug: "werknemers", anker: "vragen" },
    ] as { label: string; slug: string; anker?: string; diensten?: boolean }[],
    knop: {
      neutraal: { label: "Kennismaken", slug: "kennismaken" },
      werkgever: { label: "Kennismaken", slug: "kennismaken" },
      werknemer: { label: "Bel je casemanager", slug: "tel:" },
    },
    inloggen: "Inloggen",
    portalen: {
      werkgever: { label: "Werkgeversportaal", sub: "Verzuim volgen, ziek- en betermelden" },
      werknemer: { label: "Mijn dossier", sub: "Afspraken en documenten als werknemer" },
    },
  },

  footer: {
    bezoekadres: "Bezoekadres",
    contact: "Contact",
    alleContactgegevens: "Alle contactgegevens",
    voorWerkgevers: "Voor werkgevers",
    voorWerknemers: "Voor werknemers",
    werkgeverLinks: [
      { label: "Diensten", slug: "werkgevers", anker: "diensten" },
      { label: "Tarieven", slug: "verzuimabonnementen" },
      { label: "Kennismaken", slug: "kennismaken" },
    ] as { label: string; slug: string; anker?: string }[],
    werknemerLinks: [
      { label: "Ziek, wat nu?", slug: "verzuimprotocol" },
      { label: "Je rechten en privacy", slug: "je-rechten-en-privacy" },
      { label: "Je casemanager", slug: "je-casemanager" },
    ] as { label: string; slug: string; anker?: string }[],
    rechten: "© {jaar} React2u II B.V. Alle rechten voorbehouden. · KvK {kvk}",
    documenten: {
      privacy: "Privacyverklaring",
      voorwaarden: "Algemene voorwaarden",
      klachten: "Klachtenregeling",
      cookies: "Cookieverklaring",
    },
    cookieInstellingen: "Cookie-instellingen",
    /** De HTML-sitemap bestaat alleen in het Nederlands; in het Engels leeg, dan staat de link er niet. */
    sitemap: "Sitemap",
    keurmerken: "Certificeringen en keurmerken",
    /** Alt-teksten van de vijf keurmerklogo's, in de volgorde van KEURMERKEN in FooterR2u. */
    keurmerkAlts: ["SBCA gecertificeerde arbodienst", "DNV ISO 9001 certificaat", "DNV ISO 27001 certificaat", "DNV ISO 27701 certificaat", "Lid van OVAL"],
    logoNaarHome: "React2u, naar de homepage",
  },

  cookies: {
    titel: "Cookies en statistiek op react2u.nl",
    basis: "We gebruiken alleen functionele cookies en tellen bezoek zonder cookies.",
    /** Bij gerechtvaardigd belang (bedrijfsherkenning "altijd"): een mededeling met een uitknop. */
    optOut: "Komt je bezoek van een bedrijfsnetwerk, dan zien we welk bedrijf dat is, nooit wie. Niet nodig? Zet het uit bij Instellingen.",
    /** Bij toestemming: een vraag. */
    toestemming: "Met jouw toestemming zien we ook vanaf welk bedrijf je kijkt, nooit wie. Je keuze pas je altijd aan via Cookie-instellingen onderaan de pagina.",
    statistiek: "Statistiek",
    statistiekAltijd: "Komt je bezoek van een bedrijfsnetwerk, dan zien we welk bedrijf dat is, nooit wie. Zet dit uit als je dat niet wilt.",
    statistiekToestemming: "Met jouw toestemming zien we vanaf welk bedrijf je kijkt, nooit wie. Zo weten we welke organisaties onze site bezoeken.",
    lees: "Lees de cookieverklaring",
    prima: "Prima",
    functioneel: "Functioneel",
    functioneelUitleg: "Nodig voor een goede en veilige werking. Altijd aan.",
    keuzeOpslaan: "Keuze opslaan",
    weigeren: "Weigeren",
    instellingen: "Instellingen",
    accepteren: "Accepteren",
  },

  nietGevonden: {
    titel: "Pagina niet gevonden",
    eyebrow: "Pagina niet gevonden",
    tekst: "De pagina die je zoekt bestaat niet (meer) of is verplaatst. Geen zorgen, we helpen je graag verder.",
    sterk: "Deze pagina is even kwijt, wij niet.",
    rest: "Ga terug naar de homepage of neem contact op.",
    naarHome: "Naar de homepage",
    contact: "Contact",
  },

  formulier: {
    naam: "Naam",
    naamPlaceholder: "Je voor- en achternaam",
    email: "E-mailadres",
    emailPlaceholder: "naam@voorbeeld.nl",
    telefoon: "Telefoonnummer",
    telefoonPlaceholder: "06 12345678",
    organisatie: "Organisatie",
    organisatiePlaceholder: "Naam organisatie",
    bericht: "Bericht",
    berichtPlaceholder: "Waar kunnen we je mee helpen?",
    onderwerp: "Onderwerp",
    optioneel: "optioneel",
    verplichteVelden: "Velden met een * zijn verplicht.",
    bezig: "Versturen…",
    versturen: "Versturen",
    privacy: "Privacy",
    privacyverklaring: "privacyverklaring",
    honeypot: "website",
    sollicitatie: {
      kop: "Snel solliciteren",
      kopDirect: "Solliciteer direct",
      duur2: "2 minuten",
      duur1: "1 minuut",
      ikSolliciteerOp: "Ik solliciteer op",
      open: "Open sollicitatie",
      cv: "Cv",
      cvOptioneel: "(optioneel, mag ook later)",
      cvHint: "PDF of Word, maximaal 8 MB",
      verstuur: "Verstuur sollicitatie",
      bedankt: "Bedankt voor je sollicitatie",
      bedanktTekst: "Je hoort binnen vijf werkdagen van ons.",
      privacyVoor: "We gaan zorgvuldig om met je gegevens, lees onze ",
      privacyLink: "privacyverklaring",
      privacyNa: ".",
      bewaren: "Bewaar mijn gegevens een jaar, ook voor toekomstige vacatures.",
      bewarenUitleg: "Zonder vinkje verwijderen we ze uiterlijk vier weken na afloop van de procedure.",
    },
    contact: {
      kop: "Stuur een bericht",
      bedankt: "Bedankt voor je bericht",
      bedanktTekst: "We nemen binnen één werkdag contact met je op.",
      geenMedisch: "Deel hier geen medische informatie.",
      naamPlaceholder: "Voor- en achternaam",
      emailPlaceholder: "naam@bedrijf.nl",
      telefoonPlaceholder: "06 12 34 56 78",
    },
    fouten: {
      emailOngeldig: "Controleer je e-mailadres: dat lijkt niet te kloppen.",
      limiet: "Je hebt kort geleden al een paar keer iets verstuurd. Probeer het over een uur opnieuw, of bel ons.",
      spamcontrole: "De spamcontrole is niet gelukt. Vernieuw de pagina en probeer het opnieuw.",
      terugbelVerplicht: "Vul je naam en telefoonnummer in.",
      telefoonOngeldig: "Controleer je telefoonnummer.",
      terugbelAlgemeen: "Er ging iets mis. Bel ons gerust direct.",
      contactVerplicht: "Vul naam, e-mailadres, telefoonnummer en bericht in.",
      algemeen: "Er ging iets mis. Probeer het later opnieuw.",
      sollicitatieVerplicht: "Vul in ieder geval je naam en e-mailadres in.",
      cvTeGroot: "CV is te groot (max 8 MB).",
      cvType: "Upload je CV als PDF of Word-bestand.",
      cvUpload: "CV uploaden is niet gelukt. Probeer het opnieuw.",
      sollicitatieAlgemeen: "Er ging iets mis bij het versturen. Probeer het later opnieuw.",
      offerteVerplicht: "Vul naam, bedrijfsnaam, e-mailadres, telefoonnummer en het aantal medewerkers in.",
    },
  },

  /** De belbalk onderaan het scherm op de telefoon (werkgeverspagina's): bellen of een terugbelmoment. */
  belbalk: {
    belMijTerug: "Bel mij terug",
    sluiten: "Sluiten",
    eyebrow: "Terugbelverzoek",
    kop: "Wanneer mogen we je bellen?",
    bedankt: "Bedankt! We bellen je zoals afgesproken. Liever nu al iemand spreken? Bel {tel}.",
    wanneer: "Wanneer",
    /** Labels bij TERUGBEL_MOMENTEN (lib/formulier.ts), in dezelfde volgorde; de waarde blijft Nederlands voor het Postvak IN. */
    momenten: ["Zo snel mogelijk", "Vandaag nog", "Morgenochtend", "Morgenmiddag", "Later deze week"],
    tijden: "We bellen op werkdagen tussen 9.00 en 17.00 uur.",
  },

  /** Werken bij React2u, de vacaturepagina en de open sollicitatie. */
  vacatures: {
    seo: {
      titel: "Vacatures",
      omschrijving: "Werken bij React2u? Bekijk onze openstaande vacatures en kom werken bij dé persoonlijke arbodienstverlener in Eindhoven.",
      openTitel: "Open sollicitatie",
      openOmschrijving: "Stuur een open sollicitatie naar React2u. We komen graag in contact met talent!",
    },
    kruimelWerkenBij: "Werken bij",
    kruimelVacatures: "Vacatures",
    eyebrow: "Werken bij React2u",
    kop: "Bouw met ons aan gezond en duurzaam werk",
    intro: "Bij React2u help je zieke werknemers terug naar werk en werkgevers grip te houden op verzuim. Werk dat ertoe doet, elke dag.",
    bekijkVacatures: "Bekijk vacatures",
    openSollicitatie: "Open sollicitatie",
    micro: ["Solliciteren in 2 minuten", "Geen motivatiebrief nodig", "Reactie binnen 5 werkdagen"],
    openVacatures: "Open vacatures",
    nOpen: "{n} open",
    klantenLabel: "Je werkt voor organisaties als",
    voordelenEyebrow: "Wat je bij ons krijgt",
    voordelenKop: "Een werkgever waar je op kunt bouwen",
    voordelen: [
      { titel: "Arbeidsvoorwaarden", tekst: "Een eigen arbeidsvoorwaardenregeling, afgestemd op ons vak en ons team." },
      { titel: "Opleiding en ontwikkeling", tekst: "Opleidingen en begeleiding om je vak verder te ontwikkelen." },
      { titel: "Een eigen caseload", tekst: "Je bouwt een band op met je klanten en hun mensen, als vast gezicht." },
      { titel: "Goed ingewerkt", tekst: "Je start naast ervaren collega’s die je wegwijs maken." },
      { titel: "Korte lijnen met de bedrijfsarts", tekst: "Je werkt nauw samen met de bedrijfsarts, ook bij taakdelegatie." },
      { titel: "Kantoor in hartje Eindhoven", tekst: "Een betrokken team op loopafstand van het centrum, waar je snel schakelt." },
    ],
    werkEyebrow: "Je werk",
    werkKop: "Persoonlijk, met structuur eromheen",
    werkTekst: "Je bent de spil tussen werkgever, werknemer en bedrijfsarts. Je houdt regie over het verzuim en zorgt dat iedereen weet wat de volgende stap is.",
    werkPunten: [
      "Gesprekken met werknemers en leidinggevenden, op locatie of online",
      "Werken volgens de Wet verbetering poortwachter, met duidelijke processen",
      "Alles in één online dossier, zodat je overzicht houdt",
      "De juiste hulp inzetten, van arbeidsdeskundige tot coach",
    ],
    vacaturesEyebrow: "Vacatures",
    vacaturesKop: "Kom ons team versterken",
    geenVacaturesKop: "Nu geen openstaande vacatures",
    vacaturesTekst: "We breiden ons team uit. Voor deze functies zoeken we nu nieuwe collega’s.",
    geenVacaturesTekst: "Maar we komen altijd graag in contact met talent.",
    openKaartKop: "Open sollicitatie",
    openKaartTekst: "Vertel ons wie je bent en wat je zoekt. We nemen altijd contact met je op.",
    openKaartLink: "Stuur je sollicitatie",
    procesEyebrow: "Sollicitatieproces",
    procesKop: "Zo solliciteer je",
    procesTekst: "Helder en persoonlijk. Je weet bij elke stap waar je staat.",
    stappen: [
      { titel: "Solliciteren", tekst: "Stuur je cv en een korte motivatie via de vacature." },
      { titel: "Kennismaking", tekst: "Een eerste gesprek bij ons op kantoor." },
      { titel: "Tweede gesprek", tekst: "We gaan dieper in op de functie en je maakt kennis met het team." },
      { titel: "Aanbod", tekst: "Klikt het? Dan bespreken we je contract en startdatum." },
    ],
    solliciterenEyebrow: "Solliciteren",
    solliciterenKop: "Zin om bij ons te werken?",
    solliciterenTekst: "Kies de functie en laat je gegevens achter. Je hoort binnen vijf werkdagen van ons. Liever eerst even praten? Bel of mail Susanne.",
    solliciterenMicro: ["Geen motivatiebrief", "Eerst kennismaken mag"],
    aanspreekpunt: "Je aanspreekpunt",
    susanneRol: "Algemeen directeur",
    fotoTeamAlt: "Collega’s van React2u lachen samen aan tafel",
    fotoWerkAlt: "Drie collega’s van React2u kijken samen naar een scherm op kantoor",
    /** Alleen op een vacature zonder tekst in de taal van de pagina. */
    inHetNederlands: "Deze vacature is in het Nederlands",
    inHetNederlandsKort: "In het Nederlands",
    detail: {
      solliciteerDirect: "Solliciteer direct",
      duurtMinuut: "Duurt een minuut",
      belangrijkste: "Het belangrijkste",
      brutoPerMaand: "Bruto per maand, afhankelijk van ervaring",
      perWeek: "Per week, in overleg",
      locatieSub: "Op kantoor, op locatie en online",
      werkdagen: "5 werkdagen",
      danHoorJe: "Dan hoor je van ons",
      locatie: "Locatie",
      uren: "Uren",
      salaris: "Salaris",
      dienstverband: "Dienstverband",
      vragenBel: "Vragen? Bel Susanne",
      solliciterenKop: "Solliciteren duurt een minuut",
      solliciterenTekst: "Laat je gegevens achter en upload je cv. Je hoort binnen vijf werkdagen van ons. Een motivatiebrief is niet nodig.",
      bekijkOok: "Bekijk ook",
      allesOverWerken: "Alles over werken bij React2u",
      bekijkVacature: "Bekijk vacature",
      openKaartTekst: "Zie je jouw functie er niet tussen? Vertel ons wie je bent en wat je zoekt.",
      altijdWelkom: "Altijd welkom",
      standaardLocatie: "Eindhoven",
    },
    dienstverband: {
      FULL_TIME: "Fulltime",
      PART_TIME: "Parttime",
      "FULL_TIME,PART_TIME": "Fulltime of parttime",
      CONTRACTOR: "Freelance",
      TEMPORARY: "Tijdelijk",
      INTERN: "Stage",
    } as Record<string, string>,
    openPagina: {
      eyebrow: "Werken bij React2u",
      kop: "Open sollicitatie",
      tekst: "Staat jouw functie er niet tussen, maar denk je dat je bij ons past? We komen graag met je in contact. Laat je gegevens achter en upload je cv.",
      formKop: "Vertel ons wie je bent",
    },
  },

  /** Blokken van de werkgeverskant met vaste woorden buiten de blokdata. */
  werkgevers: {
    poortwachterMoment: "Moment",
    poortwachterJij: "Jij als werkgever",
    poortwachterWij: "React2u",
    tarievenKruimel: "Tarieven",
    offerteAanvragen: "Offerte aanvragen",
    certificeringenKruimel: "Certificeringen",
    overOnsKruimel: "Over ons",
    overReact2uKruimel: "Over React2u",
    kernwaarden: "Kernwaarden",
    /** De regel onder de prijstabel; het jaar en de datum komen uit Instellingen → Tarievenjaar. */
    geldigheid: "Tarieven {jaar}, geldig tot en met {tot}. Alle bedragen zijn exclusief btw.",
  },

  /** De labelpagina's (React2u Recover, Resist, …): de vaste woorden rond de blokdata. */
  dienstLabel: {
    kruimelDiensten: "Diensten",
    adviesgesprek: "Adviesgesprek",
    alleDiensten: "Alle diensten",
    watJeKrijgt: "Wat je krijgt",
    herken: "Herken je dit?",
    danIs: "Dan is React2u {naam} er voor jou.",
    omvat: "Wat React2u {naam} omvat",
    omvatTekst: "We zetten één onderdeel in of combineren ze tot een aanpak die past bij jouw organisatie.",
    aanpak: "Onze aanpak",
    waarom: "Waarom React2u {naam}",
    gecertificeerd: "Gecertificeerd en aangesloten",
    bekijkOok: "Bekijk ook",
    bekijk: "Bekijk",
  },

  /** Klantenstrook, klanten aan het woord en het keurmerkenblok (Gedeeld.tsx). */
  gedeeld: {
    klantenLabel: "We werken samen met:",
    ervaringenEyebrow: "Klanten aan het woord",
    ervaringenKop: "Wat klanten over ons zeggen",
    citaten: [
      {
        tekst: "Korte lijnen, snelle communicatie en altijd bereid om mee te denken. Een fijne arbodienst met oog voor zowel werkgever als werknemer.",
        naam: "Maxime Boonstra", rol: "Algemeen directeur, Kester uitzendbureau", logo: "/beeld/klanten/kester.png",
      },
      {
        tekst: "In een dynamische supermarktorganisatie is snel schakelen essentieel. Dankzij de korte lijnen, deskundige begeleiding en persoonlijke benadering ervaren wij de samenwerking als zeer prettig en betrouwbaar.",
        naam: "Afdeling HR", rol: "De Jumbo’s van Ralf & René", logo: "/beeld/klanten/jumbo.png",
      },
    ],
    kwaliteit: "Kwaliteit",
    getoetst: "Getoetst en gecertificeerd",
    kwaliteitTekst: "Je werkt met gevoelige informatie. Daarom laten we onze kwaliteit, beveiliging en privacy onafhankelijk toetsen.",
    meerCertificeringen: "Meer over onze certificeringen",
    /** Naam en omschrijving van de vijf keurmerken, in de volgorde van KEURMERKEN. */
    keurmerken: [
      { naam: "SBCA", wat: "Gecertificeerde arbodienst" },
      { naam: "ISO 9001", wat: "Kwaliteitsmanagement" },
      { naam: "ISO 27001", wat: "Informatiebeveiliging" },
      { naam: "ISO 27701", wat: "Privacy" },
      { naam: "OVAL", wat: "Branchevereniging" },
    ],
  },

  /** Kennismaken en offerte: de stappen staan in de blokdata, het formulier hier. */
  kennismaken: {
    kruimel: "Kennismaken",
    eyebrow: "Kennismaken en offerte",
    kop: "Zullen we kennismaken?",
    formKop: "Vraag een offerte aan",
    bedrijfsnaam: "Bedrijfsnaam",
    bedrijfsnaamPlaceholder: "Naam van je organisatie",
    naamPlaceholder: "Voor- en achternaam",
    functie: "Functie",
    functiePlaceholder: "Bijvoorbeeld HR-manager",
    emailPlaceholder: "naam@bedrijf.nl",
    telefoonPlaceholder: "06 12 34 56 78",
    aantal: "Aantal medewerkers",
    maakKeuze: "Maak een keuze",
    aantallen: ["1 tot 10", "11 tot 50", "51 tot 100", "101 tot 250", "Meer dan 250"],
    interesse: "Interesse",
    interessePlaceholder: "Bijvoorbeeld verzuimbegeleiding",
    toelichting: "Toelichting",
    toelichtingPlaceholder: "Waar kunnen we je mee helpen?",
    verstuur: "Verstuur aanvraag",
    voet: "Je aanvraag gaat naar ons salesteam via sales@react2u.nl. We gebruiken je gegevens alleen om contact met je op te nemen.",
    lieverBellen: "Liever direct bellen?",
    bedankt: "Bedankt voor je aanvraag",
    bedanktTekst: "We nemen binnen twee werkdagen contact met je op om kennis te maken.",
  },

  seo: {
    /** Standaardomschrijving als de pagina er geen heeft; in het Nederlands komt die uit de instellingen. */
    siteOmschrijving: "Jouw mensen, onze aandacht! React2u is een moderne arbodienst.",
    /** Zonder eigen SEO-titel op de homepage: zegt wat React2u is, niet "Home". */
    homeTitel: "Persoonlijke arbodienst en verzuimbegeleiding • React2u",
    merk: "React2u",
  },
};

export type Woordenboek = typeof nl;
